### ISSUE TITLE
Using Delegator with Dynamic Elements

### ISSUE THREAD

**Issue by AugmentBLU** [Behavior-UI/behavior-ui#38]
Hello,

I'm trying to use Delegators on elements that are created by JavaScript but not sure how that's actually done. I have an element that is generated by JS and I want to use `Reveal`, how do I apply the Delegator? 

I see that there's behavior.applyFilter() but is there something similar for Delegators?

Thanks!

**Comment by anutron** [comment]
You don't have to do anything. Delegator uses event delegation, so when you attach it to document.body, it just sits there waiting for the user to click (or whatever) and, when they do, looks to see if the element clicked has a trigger. Magic!

**Comment by AugmentBLU** [comment]
Thanks for the reply.

I'm still a bit stuck on this one. When using the following code, the trigger event is not working.

```
new Element('div', {class:'panel-heading',html: ' <a class="btn btn-default" data-trigger="dissolve" data-dissolve-target="!body #boxDissolve">click to hide box</a><div id="boxDissolve" class="box">I\'m a box!</div>'}).inject('container', 'before');
```

**Comment by anutron** [comment]
Try turning on the debug mode in your Delegator instance. It'll give you a
verbose output in the console.
