### ISSUE TITLE
Instantiate Behaviors on Remote request ? 

### ISSUE THREAD

**Issue by scramatte** [Behavior-UI/behavior-ui#41]
Hello,
How can I instantiate behaviors on remote request ?

With older Mootools  Behavior release  I've been able to do "Behavior.apply(document.body);"
But it looks that with Behavior-Ui it doesn't works anymore.

Please take a look to my code.
Note that I use  this template engine: https://github.com/tbela99/template

```javascript
new Request({
    'url': 'template.html',
    'onSuccess': function(responseText, responseXML) {
         var render = new Template().compile(responseText);
         var elt = document.id('content');
         elt.set('html', render({'title': 'hello world'})); 
         Behavior.apply(document.body);
    },
}).get();
```

**Comment by anutron** [comment]
You should have an instance of Behavior somewhere. I.e. `var myBehaviorInstance = new Behavior(...);`

Then you just reference that instance when you call apply (`myBehaviorInstance.apply(document.body)`).

If you're doing it right though, you should be using a behavior filter or a delegator for updating content, in which case you'll want to do it more like Delegator.Ajax does it by firing the `ammendDom` event: https://github.com/Behavior-UI/behavior-ui/blob/master/js/Source/Delegators/Delegator.Ajax.js#L64

You'll notice that Behavior monitors this event to apply itself to the thing changed: 
https://github.com/Behavior-UI/behavior/blob/master/Source/Behavior.js#L156

There's a corresponding `destroyDom` event that invokes all the cleanup code that filters register:
https://github.com/Behavior-UI/behavior-ui/blob/master/js/Source/Delegators/Delegator.Ajax.js#L62

You can find other examples of this kind of thing in the other filters and delegators that update the DOM. Delegator.Ajax and Form.Request being the best examples.
