### ISSUE TITLE
How can I use the form validator to match the value of one field to the value of another another

### ISSUE THREAD

**Issue by micheltobon** [Behavior-UI/behavior-ui#57]
I am trying to use the form validators but the validate-match is just not working, here is my code:
```html
                        <div class="form-group">
                            <div class="col-md-12">
                                <input id="e_mail" name="e_mail" placeholder="Email" class="form-control input-md"  type="text"
                                       data-validators="required validate-email"
                                       data-tip-location="left">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                <input id="e_mail_confirm" name="e_mail_confirm" placeholder="confirm email" 
                                       class="form-control input-md" 
                                        type="email"
                                       data-validators="required validate-match matchInput:'e_mail' matchName:'email'"
                                       data-tip-location="left">
                            </div>
                        </div>
```

**Comment by micheltobon** [comment]
I fixed it in a very unellegant way, I added the function getItems(props, preference, children, cssSelector){ ... } after all the declaration of behavior

then I added all the list that is added in Form.Validator.Extras before adding "min", "max", etc... 

horrible but working

**Comment by anutron** [comment]
Hi Michael,

First, apologies that this part is not super clear in the documentation.

For starters, the version of behavior-ui.js distributed in the git repo only includes the portions of the library and its dependencies required to work and that means it does not include Form.Validator.Extras, which is where the `validate-match` validator lives. So the first thing you'll require is a copy of that in your environment. You can build your own by modifying the grunt file in the behavior-ui repo to include More/Form.Validator.Extras in the "all" section - here: https://github.com/Behavior-UI/behavior-ui/blob/master/Gruntfile.js#L48 -  and then doing `npm install` followed by `grunt prod`. Alternately you could just append Form.Validator.Extras to the file manually, or use the `behavior-ui-standalone.js` file in the distribution and go get MooTools Core + More from MooTools.net.

Ok, the second part is easier to fix. The documentation is a little fuzzy in MooTools about how to use that validator. The short version is that it requires that you specify the properties of validators in data-validator-properies in their own attribute, like so:
```html
<input name="emailConfirm" data-validators="required validate-match"
              data-validator-properties="{matchInput:'emailInput', matchName:'email'}" class="form-control">
```
I've made a jsfiddle that illustrates all this here: http://jsfiddle.net/80b4wof7/
